### PR TITLE
B6 dgmaut 15

### PR DESCRIPTION
**Pull request by furkantasdem**
Product view added

### CODE REVIEW

**Review by nihanuygur — COMMENTED** [review]
There is no conflict for now

**Review by nzlplt — COMMENTED** [review]
it seems good, but there is always better!

**Review by GulcanA — COMMENTED** [review]
Ok. It seems good, keep working hard.

**Comment by SeyyitDuran** [comment]
Thanks for your effort, it seems okay... You can finish in the best way possible

**Pull request merged**
